### PR TITLE
add support to watts as output units

### PR DESCRIPTION
**Pull request by rkmax**
I use https://www.rapidtables.com/convert/electric/Joule_to_Watt.html as reference to
convert the joules to watts

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Thanks for this contribution!

We cannot simply label this as changing the unit, because it actually shows something fundamentally different: power instead of energy. And CPU Energy Meter has "energy" in its name, so we should make sure that we do not confuse users about this.

Furthermore, the output you propose is the average power over the whole measurement time. So we should also make sure that users to not confuse this with peak or current power, in which they also might be interested in, but which CPU Energy Meter cannot provide.

What is your use case for the way, btw.? CPU Energy Meter is currently mostly considered as a low-level measurement tool that provides raw data, and when I postprocess the data (using other tools) I would usually compute average power there if I am interested in it.

Having said that, if it its communicated clearly to the user and there is a use case for it, I certainly would not be opposed to adding this.

**Comment by rkmax** [comment]
Hi, thank you for taking the time to explain to me. my use case it's a way to see the consumption of the processor, in the same way, I can see the consumption of my graphic card and as you mentioning probably it's better to build something on top of this to show what I want.

and abusing of you time I have few of questions for you

- if this power output could be included how you suggest labeling this output to avoid user's confusion?
- if this power output could be included should be included along with the energy output instead of replacing it?
- do you think the power output is correctly calculated?

thanks in advance for you time

**Comment by PhilippWendler** [comment]
Sure, no problem. If it is labeled "average power", for example, this should be pretty clear. We could show both, and if the use case is primarily for looking at it, maybe only in the human-readable output? There it could even be in a separate column after each value. The calculation seems correct in any way.

**Comment by PhilippWendler** [comment]
Are you still interested in continuing with this?

**Comment by PhilippWendler** [comment]
Please reopen if there is still interest.

**Pull request closed without merging**
